### ISSUE TITLE
Move documentation from wiki into project's repository

### ISSUE THREAD

**Issue by egel** [egel/dotfiles#112]
### Description

As a developer,

I want to be able to integrate my MR with updating the documentation,

so that I don't have to maintain 2 different states between code base repository and documentation itself

### Subtasks

- [ ] create `/docs` directory ([info why "/docs" dir](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch))
- [ ] move all important documentation form WIKI into new directory
- [ ] disable WIKI after migration

### Additional Information

*   Depends on issue(s): -
*   Related to issue(s): -
